services:
  notification:
    build: .
    ports:
      - "5005:5005"
    depends_on:
      - valkey
    env_file:
      - .env
  valkey:
    image: valkey/valkey:8.1.3-alpine
    ports:
      - "6379:6379"
    restart: always
    command: valkey-server --save 20 1 --loglevel warning
    volumes:
      - valkey:/data

volumes:
  valkey:

networks:
  default:
    external: true
    name: appnet
